Add Dev Container
vldc-hq/vldc-bot pull request #233
Opened 2021-12-20 03:23 UTC by getjump

Dev Container open up a whole new world of possibilities:

1. It is easy to make dev environment even for frontenders, for whom currently it is hard as stated by #178 
2. You can develop even on microwave by utilizing cloud super powers of [Github Codespaces](https://github.com/features/codespaces)

There are also task and launch target defined for VS Code, so that environment is kinda complete, you just start vs code open dev container from source, click run and boom, everything just works (including debugging, and lint and stuff 🔥)

We can probably continue to improve that environment in the future (like for example when we can use Python 3.10 #221).

2021-12-20 03:30 UTC, getjump commented
We probably should store our dependencies in image, since they are not updating that frequently to speed up codespaces/local image builds.

2021-12-20 06:08 UTC, C-Pro approved these changes
👍

2021-12-22 16:02 UTC, egregors commented
Looks cool! I'll check this out next week

2021-12-27 10:38 UTC, egregors requested changes
Looks pretty cool, really. Especially debugging-in-docker and run in one click. Here are a few improvements proposals and we should provide an updated README for frontends.

2021-12-27 10:38 UTC, egregors commented on .devcontainer/Dockerfile
> +# [Optional] If your pip requirements rarely change, uncomment this section to add them to the image.
Looks like include deps into image is a good idea. We change them not so often.

2021-12-27 10:38 UTC, egregors commented on .gitignore
> -#vscode
I believe we can exclude only `launch.json` and `tasks.json` from `.gitignoge`. Personal setting should be ignored.

2021-12-28 01:45 UTC, getjump commented
@egregors I disagree that we should exclude `.vscode` from repository, IT SHOULD NOT contain personal preferences, it should contain project wise preference see https://github.com/microsoft/vscode/tree/main/.vscode (especially https://github.com/microsoft/vscode/blob/main/.vscode/settings.json) for example.

2021-12-28 02:20 UTC, C-Pro commented
> @egregors I disagree that we should exclude `.vscode` from repository, IT SHOULD NOT contain personal preferences, it should contain project wise preference

Mine does ¯\_(ツ)_/¯

2021-12-28 02:30 UTC, getjump commented
> > @egregors I disagree that we should exclude `.vscode` from repository, IT SHOULD NOT contain personal preferences, it should contain project wise preference
> 
> Mine does ¯_(ツ)_/¯

Can you provide example what's in your project settings?

2021-12-28 04:08 UTC, C-Pro commented
> > > @egregors I disagree that we should exclude `.vscode` from repository, IT SHOULD NOT contain personal preferences, it should contain project wise preference
> > 
> > 
> > Mine does ¯_(ツ)_/¯
> 
> Can you provide example what's in your project settings?

`"python.pythonPath": "/home/cpro/.pyenv/versions/3.6.6/bin/python",`

2021-12-28 11:30 UTC, egregors commented
> > > > @egregors I disagree that we should exclude `.vscode` from repository, IT SHOULD NOT contain personal preferences, it should contain project wise preference
> > > 
> > > 
> > > Mine does ¯_(ツ)_/¯
> > 
> > 
> > Can you provide example what's in your project settings?
> 
> `"python.pythonPath": "/home/cpro/.pyenv/versions/3.6.6/bin/python",`

Fair enough. Mine contains pyPath as well. ://

2021-12-28 11:59 UTC, getjump commented
@egregors @C-Pro Well, I don't like absolute paths relative to local system, probably something like pipenv/venv/etc would be better. But there's not much we can do now. Maybe later we can focus on enhancing process of development without Dev Container, but for now I have found a solution to use settings json specific to container - https://github.com/microsoft/vscode-dev-containers/blob/main/containers/go/.devcontainer/devcontainer.json#L17 . So we can safely put `.vscode/settings.json` into `.gitignore`

2021-12-28 12:04 UTC, C-Pro commented
BTW I did not set this path manually. It is changed everytime I select interpreter in vscode via dropdown menu on the bottom.

2021-12-28 12:47 UTC, getjump commented
@C-Pro Ye, that is probably not a best place to store interpreter by vscode 🤷‍♂️

2021-12-29 06:23 UTC, getjump commented
> - [ ] try to use `docker-compose-dev.yml` for devcontainer

@egregors it seems like __no fix__ to me currently. We should probably somehow remove last line, where we start bot from dev `Dockerfile` or something else.

2021-12-29 09:47 UTC, egregors commented
> > * [ ]  try to use `docker-compose-dev.yml` for devcontainer
> 
> @egregors it seems like **no fix** to me currently. We should probably somehow remove last line, where we start bot from dev `Dockerfile` or something else.

Sure, let's talk about it _after NY_ :D :D I believe we could extract it subtask into a separate issue. 

Anyway, your fixes looks grate! I gonna test it locally, just to be sure, and will merge it.

2021-12-29 09:59 UTC, getjump commented
@egregors there are a bit work still left, i accidentally commited junk comments, so probably we should merge after NY🌚🌚

2021-12-29 10:47 UTC, egregors approved these changes

2021-12-29 10:50 UTC, egregors commented
> @egregors there are a bit work still left, i accidentally commited junk comments, so probably we should merge after NY🌚🌚

@getjump If you are talking about junk in Dockerfile, I cleaned it already. But if smth else here, and you wanna freeze merge for a time, it's okey.

2021-12-29 11:49 UTC, getjump commented
@egregors Ye that's probably all. I also added new extension by Microsoft, but we can add it later maybe `"visualstudioexptteam.intellicode-api-usage-examples"`

2021-12-30 09:36 UTC, egregors commented
> @egregors Ye that's probably all. I also added new extension by Microsoft, but we can add it later maybe `"visualstudioexptteam.intellicode-api-usage-examples"`

So, in this way I gonna merge it now. @getjump could you please drop a bit more details in https://github.com/vldc-hq/vldc-bot/issues/237?

2021-12-30 09:39 UTC, merged